name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build And Push
        run: |-
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag xbbshampoo/buildspace-php:7.1-fpm \
            --file ./Dockerfile ./
